### ISSUE TITLE
Validation mail not arriving

### ISSUE THREAD

**Issue by Lytrix** [tidepool-org/blip#207]
Hi, after installing a local copy through the run servers on osx (which worked great), I can sign up for an account op blip, but a validation mail fails to arrive. The server.log states this:
<code>
2015/02/08 00:38:44 Issue sending email: Status [403] Message [<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid</Message>
  </Error>
  <RequestId>74771efc-af22-11e4-ac4d-39b074d1f64e</RequestId>
</ErrorResponse>
]
2015/02/08 00:38:44 resendSignUp: Something happened trying to resend a signup email
</code>

How can I fix this to get a local stack running?

**Comment by jebeck** [comment]
Sorry about this! We need to update the docs in a couple more places. The instructions for how to run locally are in blip's README only at the moment: https://github.com/tidepool-org/blip#running-local

LMK if that doesn't work for you.

(I assume you were using the documentation [here](http://developer.tidepool.io/starting-up-services/) mostly to get up and running?)

**Comment by Lytrix** [comment]
No problem, The README works! Wow this is really stable and responsive in comparison with other d3.js applications I work with. Great job!
