### ISSUE TITLE
Add GitHub repo URL, e.g. http://tidepool.org/products/blip/ ?

### ISSUE THREAD

**Issue by dandv** [tidepool-org/blip#216]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by kentquirk** [comment]
Dan, I'm not sure what you're asking for here. You want the blip repo to point to...our public version of blip? If so, it's actually not officially public yet -- we're still in early beta.

**Comment by dandv** [comment]
The idea was to facilitate the discovery of more information about [Blip](http://tidepool.org/products/blip/) for those who learn about it via GitHub first, in the same vein as how https://github.com/mbostock/d3 points to http://d3js.org.

**Comment by jh-bate** [comment]
The product page on the tidepool.org website. Makes sense to me, I have updated the title to point people to the blip overview on our site.
