### ISSUE TITLE
React warnings re: API and usage changes (required action for future React upgrades)

### ISSUE THREAD

**Issue by dotMR** [tidepool-org/blip#228]
When running in 'Quick Start' mode there are currently React warnings in the dev console. To eliminate the warnings some code changes are required. These changes will need to be made to support upgrades to React >= 0.13 as well.

- React.PropTypes.component is now React.PropTypes.element
- React.PropTypes.renderable is now React.PropTypes.node
- 'transferPropsTo' is deprecated

```
Warning: React.PropTypes.component will be deprecated in a future version. Use React.PropTypes.element instead.
Warning: React.PropTypes.renderable will be deprecated in a future version. Use React.PropTypes.node instead.
Warning: transferPropsTo is deprecated. See http://fb.me/react-transferpropsto for more information.
Warning: Invalid prop `patientsComponent` supplied to `Invitation`, expected a ReactElement. Check the render method of `Patients`.
```

More info:
https://facebook.github.io/react/blog/2014/10/28/react-v0.12.html

**Comment by jebeck** [comment]
Fixed in #234, thanks again!
