### ISSUE TITLE
npm test failing

### ISSUE THREAD

**Issue by dotMR** [tidepool-org/blip#229]
I recently forked the repository to review the application and all tests are currently failing on master. 
~~~
$ node -v
v0.12.2
$ npm -v
2.8.4
$ npm test

> blip@0.6.3 test /blip
> jest

Using Jest CLI v0.4.0
 FAIL  app/components/messages/__tests__/message-test.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:
  
A worker process has quit unexpectedly! This is bad news, shutting down now!
npm ERR! Test failed.  See above for more details.
~~~
It appears to be an [outstanding issue](https://github.com/facebook/jest/issues/243) with Jest / React / Node v.12 (due to an issue with JSDOM).

However I noticed the docs state: "We use Mocha with Chai for the test framework, Sinon.JS and Sinon-Chai for spy, stubs." (No mention of Jest).

Are you using Node v0.10? Should I be running the tests in another manner?

**Comment by dotMR** [comment]
I found the 'testing' branch which appears to be active and uses PhantomJS / Karma / Sinos, so I'm assuming the test package is active development and the docs in master are outdated.

**Comment by jh-bate** [comment]
@dotMR - yes sorry about that. Jest wasn't compatible with node 0.12 and have since started another testing effort with a setup that we hope will give us what we want with regards to tests. We will make sure the docs are updated as part of the testing work also

**Comment by jebeck** [comment]
As of #242 we finally have working tests on master again :)
