### ISSUE TITLE
User's password is stored in cleartext in server.log

### ISSUE THREAD

**Issue by ghost** [tidepool-org/blip#248]
I have brought up a VM running Ubuntu 14.04, successfully configured it to send mail, then successfully (it seems) started the tidepool server(s).  I had some trouble creating my account (tried a second time before the first try had expired).

In trying to find the reason for the failure (which was account already exists), I found that servers.log has the clear text of the password I entered when I attempted to create the account.

This sounds like a serious security issue: that user's passwords are visible to anyone who has access to the machine the Tidepool server is running on.

**Comment by darinkrauss** [comment]
@intelbradneedham Thanks for reporting this issue.  We take security very seriously, but unfortunately sometimes things slip through. (Fortunately, our private beta is on locked-down, encrypted servers. We are also planning on an outside security audit in the near future.)

Would it be possible for you to copy the entire log line into this issue (with the password removed, of course)? This will allow us to track down this particular issue quickly.

**Comment by jh-bate** [comment]
@darinkrauss @intelbradneedham I believe I found the offending logging and will submit a PR shortly and get it sorted. Thanks for letting us know @intelbradneedham

**Comment by HowardLook** [comment]
@darinkrauss This looks like a crufty issue that was resolved in 2015. Can we close this?

**Comment by darinkrauss** [comment]
Fixed by https://github.com/tidepool-org/shoreline/pull/20.
