### ISSUE TITLE
Indexing past the end of the array?

### ISSUE THREAD

**Issue by bearsnowstorm** [tidepool-org/blip#532]
Have just done my first upload from a Libre Freestyle using the Tidepool Uploader on Mac
Immediately on logging into the web app I get the following:
"Tidepool is stuck and isn't doing what you want it to do. We're sorry for the trouble."

The Chrome console says:
`GET https://api.tidepool.org/metadata/7a31f812a9/preferences 404 (Not Found)
api.tidepool.org/confirm/invitations/7a31f812a9:1  
GET https://api.tidepool.org/confirm/invitations/7a31f812a9 404 (Not Found)
api.tidepool.org/metadata/7a31f812a9/preferences:1  
GET https://api.tidepool.org/metadata/7a31f812a9/preferences 404 (Not Found)
api.tidepool.org/confirm/invite/7a31f812a9:1  
GET https://api.tidepool.org/confirm/invite/7a31f812a9 404 (Not Found)
api.tidepool.org/metadata/7a31f812a9/preferences:1  
GET https://api.tidepool.org/metadata/7a31f812a9/preferences 404 (Not Found)  
utils.js:335 Defaulting to display in timezone of most recent upload at 2019-02-03T17:45:43+11:00 Australia/Melbourne  
patientdata.js:993 Uncaught TypeError: Cannot read property 'type' of undefined  
    at Object.processData (patientdata.js:993)  
    at Object.componentWillReceiveProps (patientdata.js:777)  
    at d.updateComponent (ReactCompositeComponent.js:614)  
    at d.receiveComponent (ReactCompositeComponent.js:547)  
    at Object.receiveComponent (ReactReconciler.js:125)  
    at d._updateRenderedComponent (ReactCompositeComponent.js:754)  
    at d._performComponentUpdate (ReactCompositeComponent.js:724)  
    at d.updateComponent (ReactCompositeComponent.js:645)  
    at d.receiveComponent (ReactCompositeComponent.js:547)  
    at Object.receiveComponent (ReactReconciler.js:125)  `

Here's what the debugger shows:

![image](https://user-images.githubusercontent.com/19619579/52174366-c0ac7600-27e6-11e9-8c56-86f288e9c6fc.png)

It looks like we might be indexing past the end of `unprocessedPatientData`
Any thoughts on how to fix this?

**Comment by bearsnowstorm** [comment]
Working after a second upload - but might be a problem others are having too with their first attempt, so ideal if it can be fixed.

**Comment by pazaan** [comment]
Ping @cbwebdevelopment @krystophv

**Comment by cbwebdevelopment** [comment]
I think this has come up before. I’ll look into this tomorrow

**Comment by cbwebdevelopment** [comment]
@bearsnowstorm Thanks for the great error report!  This has in fact surfaced very recently in our own internal tests.  I'll try to get PR ready today for this one, and hopefully squeeze it into the upcoming release.

**Comment by bearsnowstorm** [comment]
Thanks for the fix!
