### ISSUE TITLE
Support for ADA recommended Ambulatory Glucose Profile (AGP) report

### ISSUE THREAD

**Issue by asavageiv** [tidepool-org/blip#813]
Per the [2020 ADA Standard of Medical Care in Diabetes](https://clinical.diabetesjournals.org/content/38/1/10#sec-44) the AGP report should be a standard printout. I just compared Tidepool's report with the AGP report presented in [this video](https://www.youtube.com/watch?v=9ZmsuLX5184) and 

```
6.4 Standardized, single-page glucose reports with visual cues such as the Ambulatory Glucose Profile (AGP) should be considered as a standard printout for all CGM devices. E
```

Note the sample report in the abridged standard is missing a lot of information, but the one in the video has a nice set of daily charts below the graph that would be great on the "Trends" page.

**Comment by krystophv** [comment]
@asavageiv - our progress on implementation of AGP (or similar) can be tracked here: https://tidepool.atlassian.net/browse/WEB-495

**Comment by krystophv** [comment]
AGP printouts are available now. Progress was tracked here: https://tidepool.atlassian.net/browse/WEB-2051
